import os
import xml.etree.ElementTree as ET
from collections import Counter
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def parse_xml_demand(scenario_dir: str):
    """
    Parses Configuration.rou.xml for the given scenario and computes the theoretical
    flow (in veh/h) minute-by-minute for the mainline and the ramp.
    
    Demand approach: probability-based per-lane Bernoulli process.
    Formula: probability = demand_veh_h / num_lanes / 3600
    Therefore: demand_veh_h = probability * num_lanes * 3600
    """
    xml_file = os.path.join(scenario_dir, 'Configuration.rou.xml')
    tree = ET.parse(xml_file)
    root = tree.getroot()
    
    # max time defined by the max end time in flow elements (default 7200)
    max_end = 0
    for flow in root.findall('flow'):
        try:
            end_val = float(flow.get('end', 0))
            if end_val > max_end:
                max_end = end_val
        except:
            pass
            
    max_minute = int(max_end // 60) if max_end > 0 else 120
    
    theory_main_min = np.zeros(max_minute + 1)
    theory_ramp_min = np.zeros(max_minute + 1)
    
    # Iterate through each flow definition
    for flow in root.findall('flow'):
        prob = float(flow.get('probability', 0))
        begin = float(flow.get('begin', 0))
        end = float(flow.get('end', 7200)) # Default end is 7200s if not specified
        edge_from = flow.get('from', '')
        
        # Calculate vehicle per hour for this specific flow definition
        # Since this is defined per lane, we just add it to our minute buckets
        # total_demand = sum of all probabilities * 3600
        demand_veh_h = prob * 3600.0
        
        start_min = int(begin // 60)
        end_min = int(end // 60)
        
        for m in range(start_min, end_min):
            if m <= max_minute:
                if edge_from in ['E_upstream', 'E_main_before']:
                    theory_main_min[m] += demand_veh_h
                elif edge_from == 'E_ramp':
                    theory_ramp_min[m] += demand_veh_h
                    
    return theory_main_min[:max_minute], theory_ramp_min[:max_minute]


def analyze_and_plot_demand(scenario: str, controller_name: str, vehicle_flows: list, 
                            data_source_dir: str, vis_dir: str):
    """
    Generates comparison tables and plots for theoretical vs simulated demand.
    
    Args:
        scenario: Demand scenario name (e.g. 'stationary')
        controller_name: Name of the controller evaluated
        vehicle_flows: List of tuples (timestamp, edge, veh_type) generated by the environment
        data_source_dir: Path to the 1_data_source folder containing scenario configs
        vis_dir: Path to the output directory for plots
    """
    # 1. Parse theoretical demand directly from the XML
    scenario_dir = os.path.join(data_source_dir, scenario)
    theory_main, theory_ramp = parse_xml_demand(scenario_dir)
    
    # 2. Extract simulated demand
    # Aggregate flows by time (minute) and edge
    times = [int(t // 60) for t, edge, vtype in vehicle_flows]
    edges = [edge for t, edge, vtype in vehicle_flows]
    
    # Count vehicles per minute per edge
    flow_counter = Counter(zip(times, edges))
    
    max_time = len(theory_main)
    if times:
        max_time = max(max_time, max(times) + 1)
        
    actual_mainline = np.zeros(max_time)
    actual_ramp = np.zeros(max_time)
    
    # Mainline vehicles depart on E_upstream (loading zone)
    # They could theoretically depart on 'E_main_before' if config changes
    MAINLINE_EDGES = {'E_main_before', 'E_upstream'}
    
    for (minute, edge), count in flow_counter.items():
        if minute < max_time:
            # Convert veh/min to veh/h
            hourly_flow = count * 60
            if edge in MAINLINE_EDGES:
                actual_mainline[minute] += hourly_flow
            elif edge == 'E_ramp':
                actual_ramp[minute] += hourly_flow

    # Extend theoretical arrays if actual simulation ran longer
    if max_time > len(theory_main):
        theory_main = np.pad(theory_main, (0, max_time - len(theory_main)), 'edge')
        theory_ramp = np.pad(theory_ramp, (0, max_time - len(theory_ramp)), 'edge')

    # --- TEXT-BASED DEMAND LOG ---
    print(f"\n    {'-'*60}")
    print(f"    XML DEMAND LOG: {controller_name} / {scenario}")
    print(f"    {'-'*60}")
    
    # Edge breakdown: which edges saw departures?
    unique_edges = Counter(edges)
    print(f"    Departures by edge:")
    for e, c in unique_edges.most_common():
        print(f"      {e:40s} : {c:6d} veh")
        
    total_sim_main = np.sum(actual_mainline)
    total_sim_ramp = np.sum(actual_ramp)
    total_theory_main = np.sum(theory_main[:len(actual_mainline)])
    total_theory_ramp = np.sum(theory_ramp[:len(actual_ramp)])
    
    # Total vehicles (veh/h summed over minutes → divide by 60)
    print(f"    Mainline total vehicles: theory={total_theory_main/60:.0f}  simulated={total_sim_main/60:.0f}  delta={(total_sim_main - total_theory_main)/60:+.0f}")
    print(f"    Ramp     total vehicles: theory={total_theory_ramp/60:.0f}  simulated={total_sim_ramp/60:.0f}  delta={(total_sim_ramp - total_theory_ramp)/60:+.0f}")
    
    # Per-interval comparison (every 10 min)
    print(f"    \n    Per-interval comparison (10-min blocks):")
    print(f"    {'Interval':>12s}  {'Main XML':>12s}  {'Main sim':>10s}  {'delta main':>10s}  {'Ramp XML':>12s}  {'Ramp sim':>10s}  {'delta ramp':>10s}")
    
    for block_start in range(0, min(120, len(theory_main)), 10):
        block_end = min(block_start + 10, len(theory_main))
        th_m = np.mean(theory_main[block_start:block_end])
        th_r = np.mean(theory_ramp[block_start:block_end])
        
        sim_m_slice = actual_mainline[block_start:block_end]
        sim_r_slice = actual_ramp[block_start:block_end]
        
        sim_m = np.mean(sim_m_slice) if len(sim_m_slice) > 0 else 0
        sim_r = np.mean(sim_r_slice) if len(sim_r_slice) > 0 else 0
        
        lbl = f"{block_start}-{block_end} min"
        print(f"    {lbl:>12s}  {th_m:>12.0f}  {sim_m:>10.0f}  {sim_m-th_m:>+10.0f}  {th_r:>12.0f}  {sim_r:>10.0f}  {sim_r-th_r:>+10.0f}")
        
    # MAE summary
    mae_main = np.mean(np.abs(actual_mainline - theory_main[:len(actual_mainline)]))
    mae_ramp = np.mean(np.abs(actual_ramp - theory_ramp[:len(actual_ramp)]))
    print(f"    MAE mainline (simulated vs XML): {mae_main:.0f} veh/h    MAE ramp: {mae_ramp:.0f} veh/h")
    print(f"    {'-'*60}")
    
    # --- Save plot ---
    time_axis_actual = range(len(actual_mainline))
    time_axis_theory = range(len(theory_main))
    
    fig, (ax_main, ax_ramp) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
    
    ax_main.plot(time_axis_theory, theory_main, "b--", linewidth=2, label="XML Theoretical Demand")
    ax_main.plot(time_axis_actual, actual_mainline, "r-", alpha=0.8, label="Simulated Actual")
    ax_main.set_title(f"Mainline Flow - {controller_name} ({scenario})")
    ax_main.set_ylabel("Flow (veh/h)")
    ax_main.legend()
    ax_main.grid(True, alpha=0.3)
    
    ax_ramp.plot(time_axis_theory, theory_ramp, "b--", linewidth=2, label="XML Theoretical Demand")
    ax_ramp.plot(time_axis_actual, actual_ramp, "r-", alpha=0.8, label="Simulated Actual")
    ax_ramp.set_title(f"Ramp Flow - {controller_name} ({scenario})")
    ax_ramp.set_xlabel("Time (min)")
    ax_ramp.set_ylabel("Flow (veh/h)")
    ax_ramp.legend()
    ax_ramp.grid(True, alpha=0.3)
    
    plt.tight_layout()
    os.makedirs(vis_dir, exist_ok=True)
    plot_path = os.path.join(vis_dir, f"demand_vs_simulated_{scenario}_{controller_name}.png")
    plt.savefig(plot_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"    Demand comparison plot saved to: {plot_path}")
